### ISSUE TITLE
Does not work for me

### ISSUE THREAD

**Issue by mikebarkmin** [concept-not-found/react-cosmos-reach-router-proxy#1]
I have tried to use your package, but I can not get it to work. I have configured it accordingly to your README.

When I investigate the code with React Dev Tools, I see that a ServerLocation component is added, but further down the tree the location context seems to be different.

Here are the files which I have tried:

App.js
```
import React from 'react';
import { Router } from '@reach/router';

import Member from './Member';
import MemberCreate from './MemberCreate';
import Members from './Members';

class App extends React.Component {
  render() {
    return (
      <Router>
        <Member path="/member/:id" />
        <MemberCreate path="/member/create" />
        <Members path="/members" />
      </Router>
    );
  }
}

export default App;
```

App.fixture.js
```
import App from '../src/App';

export default [
  {
    component: App,
    reduxState: {},
    url: '/members'
  }
];
```
Package Versions
```
@reach/router@1.2.1
react-cosmos@4.6.4
```

**Comment by Pyrolistical** [comment]
Sorry, not maintaining this any more. This is also more complicated than it needs to be. It shouldn't be using ServerLocation, it use https://reach.tech/router/api/createMemorySource instead
